sudo: required
language: rust

cache: cargo

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - cmake
        sources:
            - kalakris-cmake

rust:
    - stable

before_install:
    - export PATH=$HOME/.cargo/bin:$PATH
    - cargo install cargo-travis

script:
    - cargo fmt --all -- --check
    - cargo build
    - cargo test

after_success:
    - cargo coveralls
